### PR TITLE
accept-ra: do not enable by default, default to unset

### PR DESCRIPTION
**Pull request by raharper**
Do not always emit an IPv6AcceptRA value into network configurations.
Systemd-networkd defaults to kernel value as long as the value stays
unset in the configuration.  When IPv6AcceptRA is enabled in systemd
this makes networkd wait 10 seconds for potential RAs to arrive.  This
delays boot by 10 seconds always whether or not the network has an
IPV6 Router running.  Leaving things unsets keeps existing behavior
of Ubuntu systems where RAs are accepted and processed at the time
they are received and boot is not delayed by waiting for an RA to arrive.

If users want to forcibly enable or disable, they may do so by including
a value for accept-ra in their yaml configuraion.

LP: #1732002

### CODE REVIEW

**Comment by cyphermox** [comment]
The bond and bridge accept-RA handling is unnecessary, the earlier cases already write it.

I've started to merge this already, applying the fixes.

**Comment by raharper** [comment]
> The bond and bridge accept-RA handling is unnecessary, the earlier cases already write it.

Yes, I should have just dropped it from emitting the IPv6AcceptRA=no by default.

thanks

**Comment by cyphermox** [comment]
Closing; I put together https://github.com/CanonicalLtd/netplan/pull/20 with the changes; what do you think?

**Comment by raharper** [comment]
Thanks, that looks great.

**Pull request closed without merging**
