### PR TITLE
Doc: Mark versions of new config keys

### PR DESCRIPTION
**Pull request by slyon**
## Description
Documenting the first version when a new feature (config key) was introduced down to `v0.96`. No new keys were introduced in 0.96.

## Checklist

- [x] Runs `make check` successfully.
- [x] Retains 100% code coverage (`make check-coverage`).
- [ ] New/changed keys in YAML format are documented.
- [ ] \(Optional\) Closes an open bug in Launchpad.

### CODE REVIEW

**Comment by vorlonofportland** [comment]
I agree that an underline of a dash is a strange rendering choice.  What about either putting the dash outside the underline, or omitting the dash completely given that the underline itself will already provide visual separation?

**Comment by vorlonofportland** [comment]
+1 on the latest proposal.

**Comment by slyon** [comment]
Thanks, I will adopt the documentation accordingly!

**Comment by slyon** [comment]
@sil2100 This should be ready for merging now.
I've also updated the `validate_docs.sh` test, to account for the new number of config keys.

**Pull request merged**
