### PR TITLE
Add option `emit-lldp` for networkd backend

### PR DESCRIPTION
**Pull request by Frankkkkk**
## Description
It is actually sadly not possible to say to networkd to send lldp packets on its interfaces. This is really useful in a profesional environment.

## Checklist

- [x] Runs `make check` successfully.
- [x] Retains 100% code coverage (`make check-coverage`).
- [x] New/changed keys in YAML format are documented.
- [x] \(Optional\) Closes an open bug in Launchpad.[BUG 1862607](https://bugs.launchpad.net/netplan/+bug/1862607)

### CODE REVIEW

**Comment by Frankkkkk** [comment]
Hi @sil2100 , any chance you could check this PR ?
Thanks and have a nice week !
Cheers

**Comment by sil2100** [comment]
Hey! Sure thing, sorry it took so long. I'll take a look tomorrow.

**Comment by Frankkkkk** [comment]
Hi !,
no worries ;-)
For the LLDP option, i chose not to put it here as I find that receiving LLDP requests is quite transparent to the system (i.e. systemd just stores them and nothing more), contrary to emiting them which some people may not want (and/or for privacy issues, hence the default=off). However in an entreprise environment it is very useful.

However, it is true that it could be maybe useful to allow the change this param to `true` (i.e. receive from everybody, not just routers). If that's fine with you i propose you that I do this change in another PR ?

Cheers

**Comment by sil2100** [comment]
Sounds like a plan! Thanks!

**Pull request merged**
