### PR TITLE
Support hashed passwords for 802.1x

### PR DESCRIPTION
**Pull request by fluffy**
## Description

Fixes https://bugs.launchpad.net/netplan/+bug/1819831

## Checklist

- [ x] Runs `make check` successfully.
- [ ] Retains 100% code coverage (`make check-coverage`).
- [ x] New/changed keys in YAML format are documented.
- [ x] \(Optional\) Closes an open bug in Launchpad.

### CODE REVIEW

**Comment by fluffy** [comment]
ah, I missed that. Thanks. I will fix that and update the PR

**Comment by fluffy** [comment]
OK I think I got the indentation fixed.

**Comment by cyphermox** [comment]
Thanks. Could you also please add tests to tests/generator/test_auth.py so we can maintain 100% coverage? :)

**Comment by sil2100** [comment]
I have opened https://github.com/CanonicalLtd/netplan/pull/92 that merges these changes + the test coverage additions.

**Comment by manicmonkey** [comment]
Presumably this is obsoleted by the merge of #92 ?

**Comment by cyphermox** [comment]
yes, this is obsoleted by the merge of #92 . Closing.

**Pull request closed without merging**
