### PR TITLE
[snap] Add 'snap/snapcraft.yaml'

### PR DESCRIPTION
**Pull request by slashdd**
A snap is a bundle of your app and its dependencies that works without modification across Linux.
Snaps are discoverable and installable from the Snap store.e

### CODE REVIEW

**Comment by slashdd** [comment]
Push as agreed with cyphermox this morning.

**Comment by cyphermox** [comment]
Looks good to me (but I had already reviewed some parts of it). I have small nitpicks however:

The encoding of python version in PYTHONPATH isn't ideal; can we have that point to usr/lib/python3 instead, or wherever it's not specifically python3.5?

Furthermore, there's a potential issue there building because of pep8/pycodestyle, different releases of Ubuntu have different libraries available for that. This will require some work on the build side to make sure the right one to use can be detected.

**Comment by slashdd** [comment]
Since pycodestyle has been first introduces starting with Bionic, I had to use pep8 in Xenial for the snap testing. I think it might be safe to rely on pycodestyle only since netplan is normally install on release w/ Bionic and late ?

**Comment by slashdd** [comment]
IIRC pep8 is the old name. Now its pycodestyle (formerly called pep8)

**Comment by slashdd** [comment]
- Changed the `PYTHONPATH` to `$SNAP/usr/lib/python3/dist-packages`
- Changed snap name from `netplan-io` to `netplan`. Otherwise it creates a binary in the form of `/snap/bin/netplan-io.netplan` instead of `/snap/bin/netplan`

Note
In the deb world `netplan` is a totally different project `network server for `plan', but chances this package will be snap one day are low IMHO.

**Comment by cyphermox** [comment]
WFM. merging.

**Pull request merged**
